import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import { ReactNode } from 'react';
import { Toaster } from 'react-hot-toast';
import { AuthStoreInitializer } from '@/store/auth';
import { cookies } from 'next/headers';
import { getApi } from '@/lib/api';

const PontanoSansFont = localFont({
  src: '../public/fonts/Pontano_Sans/PontanoSans-VariableFont_wght.ttf',
  variable: '--font-pontano-sans',
})

const PinyonScriptFont = localFont({
  src: '../public/fonts/Pinyon_Script/PinyonScript-Regular.ttf',
  variable: '--font-pinyon-script',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const cookieStore = await cookies();
  // const api = getApi();
  const token = cookieStore.get('auth_token')?.value || null;
  console.log(token);
  const user = await getApi(token ?? '').user.me();

  console.log(user);


  return (
    <html lang="fr">
      <body
        className={`${PontanoSansFont.variable} ${PinyonScriptFont.variable} antialiased`}
      >
        <AuthStoreInitializer token={token} user={null} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
